spring:
  application:
    name: customer-service
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
#  config:
#    import: optional:configserver:http://root:s3cr3t@localhost:8081