spring:
  application:
    name: registry-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8081/
      username: root
      password: s3cr3t
      name: registry-service
  profiles:
    active: dev