spring:
  application:
    name: shopping-service
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8081/
      username: root
      password: s3cr3t
      name: shopping-service
    openfeign:
      circuitbreaker:
        enabled: true
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8086