server:
  port: 8081

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JOSECONDORI5/api-store/config-data.git
          search-paths:
            - customer-service
            - product-service
            - shopping-service
            - registry-service
            - gateway-service
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
      label: main
  security:
    user:
      name: root
      password: s3cr3t
